//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.01 at 02:04:49 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.interieur.gouv.fr/ACTES#v1.1-20040216", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.gouv.interieur.actes_v1;
